### ISSUE TITLE
[依頼]最終課題挙動確認

### ISSUE THREAD

**Issue by makkei0526** [makkei0526/freemarket_sample_71f#127]
- URL/ID/Pass
  - ElasticIP:18.177.9.38
  - basic認証
  - ID:admin
  - パスワード：2222

- テスト用アカウント等
  - 購入者用
    - メールアドレス:test@gmail.com
    - パスワード:test1111
  - 出品者用
    - メールアドレス名:test2@gmail.com
    - パスワード:test1111
- 購入用カード情報
  - 番号：4242424242424242
  - 期限：セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、上記に購入カード情報が記載されていなかったため、挙動確認が行えませんでした。
（次回チェックの方へ：ユーザー登録、マイページの項目のみチェック済みです）

購入カード情報を記載の上、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by makkei0526** [comment]
購入用カード情報を追記いたしました。ご確認よろしくお願いします！

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
